# Generated by Django 5.0.1 on 2024-01-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_usersite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSite',
        ),
    ]
