# Generated by Django 5.0.1 on 2024-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_usersite'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
