# Generated by Django 5.0.1 on 2024-01-24 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_site_name_datasize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasize',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='data', to='website.site'),
        ),
    ]
