# Generated by Django 5.0.1 on 2024-01-24 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_datasize_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasize',
            old_name='received_data',
            new_name='received_data_size',
        ),
    ]
