# Generated by Django 5.0.1 on 2024-01-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_rename_received_data_datasize_received_data_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasize',
            name='received_data_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='datasize',
            name='sent_data_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
